apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: domino
  namespace: domino
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: domino
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: TCP
          port: 3000
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 5432
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
        - protocol: TCP
          port: 443
