import type { ApiRouteContract } from "./contract";

export const claimRouteContracts = [
  {
    method: "post",
    path: "/v1/products/{id}/notes",
    operationId: "createProductNote",
    summary: "Add a product note",
    tag: "Notes",
    permissions: ["notes:write"],
    request: { schema: "NoteInput" },
    success: 201,
  },
  {
    method: "get",
    path: "/v1/products/{id}/notes",
    operationId: "listProductNotes",
    summary: "List product notes",
    tag: "Notes",
    permissions: ["notes:read"],
    query: "NoteListQuery",
  },
  {
    method: "post",
    path: "/v1/products/{id}/claims",
    operationId: "createClaim",
    summary: "Create a claim draft",
    tag: "Claims",
    permissions: ["claims:create"],
    request: { schema: "ClaimCreateInput" },
    success: 201,
  },
  {
    method: "get",
    path: "/v1/claims",
    operationId: "listClaims",
    summary: "List accessible claims",
    tag: "Claims",
    permissions: ["claims:read"],
    query: "ClaimListQuery",
    claimScoped: true,
  },
  {
    method: "get",
    path: "/v1/claims/{id}",
    operationId: "getClaim",
    summary: "Get a claim and its timeline",
    tag: "Claims",
    permissions: ["claims:read"],
    claimScoped: true,
  },
  {
    method: "get",
    path: "/v1/claims/{id}/notes",
    operationId: "listClaimNotes",
    summary: "List notes for an accessible claim",
    tag: "Notes",
    permissions: ["notes:read"],
    query: "NoteListQuery",
    claimScoped: true,
  },
  {
    method: "post",
    path: "/v1/claims/{id}/notes",
    operationId: "createClaimNote",
    summary: "Add a note to an accessible claim",
    tag: "Notes",
    permissions: ["notes:write"],
    request: { schema: "NoteInput" },
    success: 201,
    claimScoped: true,
  },
  {
    method: "patch",
    path: "/v1/claims/{id}",
    operationId: "updateClaim",
    summary: "Update claim status or resolution",
    tag: "Claims",
    permissions: ["claims:manage"],
    request: { schema: "ClaimUpdateInput" },
    claimScoped: true,
  },
] satisfies ApiRouteContract[];
