import type { ApiRouteContract } from "./contract";

export const documentRouteContracts = [
  {
    method: "get",
    path: "/v1/documents",
    operationId: "listDocuments",
    summary: "List document references",
    tag: "Documents",
    permissions: ["documents:read"],
    query: "DocumentListQuery",
    claimScoped: true,
  },
  {
    method: "post",
    path: "/v1/documents/upload",
    operationId: "attachDocumentStream",
    summary: "Stream a document attachment",
    tag: "Documents",
    permissions: ["documents:attach"],
    query: "StreamedDocumentUploadQuery",
    request: { contentType: "application/octet-stream", binary: true },
    success: 201,
    claimScoped: true,
    description:
      "Streams up to 50 MiB without buffering the whole file. The configured Paperless-ngx store is authoritative when selected.",
  },
  {
    method: "post",
    path: "/v1/documents",
    operationId: "attachDocumentMultipart",
    summary: "Upload a multipart document attachment",
    tag: "Documents",
    permissions: ["documents:attach"],
    request: { contentType: "multipart/form-data", binary: true },
    success: 201,
    claimScoped: true,
    description:
      "Accepts a `file` part up to 50 MiB plus optional name, kind, backend, productId, and claimId fields.",
  },
  {
    method: "post",
    path: "/v1/documents/link-paperless",
    operationId: "linkPaperlessDocument",
    summary: "Link an existing Paperless-ngx document",
    tag: "Documents",
    permissions: ["documents:attach", "paperless:discover"],
    request: { schema: "PaperlessLinkInput" },
    success: 201,
    claimScoped: true,
  },
  {
    method: "get",
    path: "/v1/paperless/search",
    operationId: "searchPaperlessDocuments",
    summary: "Search the configured Paperless-ngx store",
    tag: "Documents",
    permissions: ["documents:read", "paperless:discover"],
    query: "PaperlessSearchQuery",
    rateLimit: "120 requests per actor per minute",
  },
  {
    method: "post",
    path: "/v1/documents/{id}/refresh",
    operationId: "refreshPaperlessDocument",
    summary: "Refresh Paperless-ngx document metadata",
    tag: "Documents",
    permissions: ["documents:read", "paperless:discover"],
    claimScoped: true,
  },
  {
    method: "get",
    path: "/v1/documents/{id}/content",
    operationId: "getDocumentContent",
    summary: "Download local document content",
    tag: "Documents",
    permissions: ["documents:read"],
    claimScoped: true,
    responseContentType: "application/octet-stream",
  },
  {
    method: "delete",
    path: "/v1/documents/{id}",
    operationId: "trashDocument",
    summary: "Move a document to trash",
    tag: "Documents",
    permissions: ["documents:manage"],
    claimScoped: true,
  },
  {
    method: "post",
    path: "/v1/documents/{id}/restore",
    operationId: "restoreDocument",
    summary: "Restore a trashed document",
    tag: "Documents",
    permissions: ["documents:manage"],
    claimScoped: true,
  },
] satisfies ApiRouteContract[];
