import type { ApiRouteContract } from "./contract";

export const productRouteContracts = [
  {
    method: "get",
    path: "/v1/products",
    operationId: "searchProducts",
    summary: "Search and filter products",
    tag: "Products",
    permissions: ["products:read OR warranties:read"],
    query: "ProductSearchQuery",
    rateLimit: "240 requests per actor per minute",
  },
  {
    method: "get",
    path: "/v1/products/{id}",
    operationId: "getProduct",
    summary: "Get a product",
    tag: "Products",
    permissions: ["products:read OR warranties:read"],
  },
  {
    method: "post",
    path: "/v1/products",
    operationId: "createProduct",
    summary: "Create a product",
    tag: "Products",
    permissions: ["products:create OR warranties:write"],
    request: { schema: "ProductInput" },
    success: 201,
  },
  {
    method: "patch",
    path: "/v1/products/{id}",
    operationId: "updateProduct",
    summary: "Update product metadata",
    tag: "Products",
    permissions: ["products:manage OR warranties:write"],
    request: { schema: "ProductUpdateInput" },
  },
  {
    method: "patch",
    path: "/v1/products/{id}/record",
    operationId: "updateProductRecord",
    summary: "Update product and warranty metadata together",
    tag: "Products",
    permissions: ["products:manage OR warranties:write"],
    request: { schema: "ProductRecordUpdateInput" },
  },
  {
    method: "delete",
    path: "/v1/products/{id}",
    operationId: "archiveProduct",
    summary: "Move a product to the archive",
    tag: "Products",
    permissions: ["products:manage OR warranties:write"],
  },
  {
    method: "post",
    path: "/v1/products/{id}/restore",
    operationId: "restoreProduct",
    summary: "Restore an archived product",
    tag: "Products",
    permissions: ["products:manage OR warranties:write"],
  },
  {
    method: "post",
    path: "/v1/products/{id}/warranties",
    operationId: "createWarranty",
    summary: "Add warranty coverage",
    tag: "Warranties",
    permissions: ["warranties:create OR warranties:write"],
    request: { schema: "WarrantyInput" },
    success: 201,
  },
  {
    method: "patch",
    path: "/v1/warranties/{id}",
    operationId: "updateWarranty",
    summary: "Update warranty coverage",
    tag: "Warranties",
    permissions: ["warranties:manage OR warranties:write"],
    request: { schema: "WarrantyUpdateInput" },
  },
  {
    method: "delete",
    path: "/v1/warranties/{id}",
    operationId: "deleteWarranty",
    summary: "Delete warranty coverage",
    tag: "Warranties",
    permissions: ["warranties:manage OR warranties:write"],
  },
] satisfies ApiRouteContract[];
